CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk       # [osx]
  
c_compiler:
 - vs2019                     # [win]
 
cxx_compiler:
 - vs2019                     # [win]

cxx_compiler_version:
 - 12.2.0                     # [linux]